import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import QueryProvider from '@/providers/query-provider'
import Header from "@/components/shared/Header";
import Footer from '@/components/shared/Footer';
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mini-Commerce",
  description: "Generated by create next app",
  openGraph: {
    title: "Mini-Commerce Store",
    description: "An e-commerce platform for listing and managing products.",
    images: ["/images/og-image.jpg"],
    url: "https://smada-store.vercel.app",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <QueryProvider>
          <Header />
          {children}
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
